name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      runLint:
        description: 'Run the static linter'     
        required: false
        default: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build in the dev container image
        uses: devcontainers/ci@v0.3
        with:
            imageName: ghcr.io/gradleup/gradleup.github.io-builder
            cacheFrom: ghcr.io/gradleup/gradleup.github.io-builder
            push: never
            runCmd: |
              mkdocs build
            env: |
              FULL_BUILD=true
      
      - name: Lint the static site
        uses: anishathalye/proof-html@v2
        if: ${{ inputs.runLint }}
        with:
          directory: ./_site
          enforce_https: false
          tokens: |
            {"https://github.com": "${{ secrets.GITHUB_TOKEN }}"}
          ignore_url: |
             https://fonts.gstatic.com
